build:
  version: "1.0"

accounts:
  message: "Welcome to babyBanking accounts related prod APIs"
  contactDetails:
    name: "Ola - Developer"
    email: "Olaraji29@gmail.com"
  onCallSupport:
    -(+234)475-485
    -(+234)398-280