build:
  version: "2.0"

accounts:
  message: "Welcome to babyBanking accounts related QA APIs"
  contactDetails:
    name: "Husaini - QA Lead"
    email: "Husainiraji29@gmail.com"
  onCallSupport:
    -(+234)485-385
    -(+234)597-288