#spring.application.name=configserver
spring:
  application:
    name: "configserver"
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
#          search-location: "classpath:/config"
          search-location: "file:///C://Users//Kehinde.Raji//Documents//config"

server:
  port: 8071